### ISSUE TITLE
[FIX] 2차 스프린트 QA

### ISSUE THREAD

**Issue by MoonsuKang** [Team-Clody/Clody_Android#169]
## 💡 Issue

- 2차 스프린트 QA

## 📝 todo

- [x] Lottie animation 수정
- [x] Clover Dialog 외부 영역 수정
- [x] ToolTip 위치 조정
- [x] 일기작성 component 크기 및 위치 조정
- [x] 온보딩 개인정보처리 방침, 서비스 이용약관 연결
- [x] 로딩화면에서 뒤로가기 로직 수정
- [x] 답변화면에서 뒤로가기 로직 수정
