### ISSUE TITLE
[FIX] 2차 스프린트 QA 반영

### ISSUE THREAD

**Issue by SYAAINN** [Team-Clody/Clody_Android#175]
## 💡 Issue

- 2차 스프린트 QA - 디자인

## 📝 todo

- [x] 앱 이름 CLODY -> Clody 로 변경
- [x] 폰트 및 색상 설정 피그마와 비교하여 확인하기
- [x] DailyDiaryCard 내 간격 조정하기
- [x] 토스트 메시지 체크 아이콘 (ic_toast_check_on_18.xml) 교체
- [ ] 답장확인 버튼 사이즈 조정해보기
- [x] "설정 > 알림설정" 토글 디자인 비슷하게 바꿔보기
- [x] "설정 > 알림설정" 알람시간 변경 터치영역 개선 및 리플효과 제거
- [x] "설정 > 알림설정" 알람시간 변경 타임피커 타이틀 수정
- [x] "설정 > 알림설정" 타임피커 간격 줄이기
- [x] 리스트뷰, 캘린더뷰 탑앱바 위치 통일

------
<추가>

- [x] "온보딩 > 닉네임 설정" 글자수 카운트 컴포넌트 밑으로 내려가있는거 올리기
