### ISSUE TITLE
[FEAT] "설정 > 프로필 및 계정관리" 에러대응

### ISSUE THREAD

**Issue by SYAAINN** [Team-Clody/Clody_Android#179]
## 💡 Issue

- "설정 > 프로필 및 계정관리" 에러 대응

## 📝 todo

- [x] **[ 뷰 교체 ]** "설정 > 프로필 및 계정관리" 유저 정보 받아오기 실패 시 
- [x] **[ 팝업 ]** "설정 > 프로필 및 계정관리" 닉네임 변경 실패 시 
- [x] **[ 팝업 ]** "설정 > 프로필 및 계정관리" 회원탈퇴 실패 시
