### ISSUE TITLE
[REFACTOR] ConstraintLayout 사용을 제거하고 UI 리팩토링을 실시합니다.

### ISSUE THREAD

**Issue by MoonsuKang** [Team-Clody/Clody_Android#215]
## 💡 Issue

- ConstraintLayout으로 구성했던 UI를 Compose 기본 레이아웃으로 리팩토링합니다.
 
## 📝 todo

- [x] 비율로 Padding 적용
  - `heightForScreenPercentage` 확장함수 생성

- [x] 담당 스크린을 Constraint -> Scaffold로 변경

- [x] **WriteDiaryScreen**
  - `Smart Recomposition` 적용
    - **key** 사용
    - **derivedStateOf**를 사용해 필드를 캐시해서 불필요한 연산을 줄임

  - `WriteDiaryTextField` 수정
    - handleColor 색상 변경 
    - 외부영역 클릭 시 Focus 해제
    - 50글자 초과 Input시 경고 메시지

- [x] **GuideScreen**
  - `Home`으로 이동할 때 애니메이션 적용

- [x] `Loading`, `Failure`, `Success` 구조 일치화

- [x] `ReplyScreen` 스크롤 영역 수정
