### ISSUE TITLE
[HOTFIX] Conflict 해결

### ISSUE THREAD

**Issue by SYAAINN** [Team-Clody/Clody_Android#52]
## 💡 Issue

- Conflict 해결

## 📝 todo

- [x] 함수 파라미터 삭제 
- [x] 중첩 import문 삭제
- [x] viewModel 전역 선언화
