### ISSUE TITLE
[Fix] color, font asset setting naming fix 

### ISSUE THREAD

**Issue by SYAAINN** [Team-Clody/Clody_Android#6]
## 💡 Issue
- color, font asset setting 과정에서 미처 확인못한 부분이 있어 조금 수정하려 합니다.

## 📝 todo
- [x] LocalTypography -> LocalClodyTypography 수정으로 통일성 개선
- [x] LocalTypography 부분 줄바꿈 제거
- [x] CLODYTheme 함수 MaterialTheme 들여쓰기 제거
- [x] color -> colors 로 통일
